REDIS_HOST=localhost
REDIS_PORT=6379

DB_HOST=localhost
DB_PORT=3306
DB_USERNAME=banking_user
DB_PASSWORD=banking@4642

KAFKA_BOOTSTRAP_SERVERS=localhost:9092

RAZORPAY_KEY_ID=rzp_test_TXEglh6GbeRMid
RAZORPAY_KEY_SECRET=oGjIavEhQ8XGot3SLmeJcQYa